spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3308/auth_service
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

jwt:
  expiryDate: 300000

# Actuator properties
management:
  health:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
app:
  logs:
    fileLocation: C:\Users\isset\SpringBootProjects-Java\microservices-1\microservices-logs # Path to your local machine directory
